# å¯¼èˆªæ 
menu: # å¯¼èˆªæ ä¸Šçš„é“¾æ¥
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

home:
  style: detail # default, detail

favicon: # Favicon æ–‡ä»¶è·¯å¾„ï¼Œç›¸å¯¹äº /source ç›®å½•ï¼ˆè‹¥ä½ çš„ Favicon æ–‡ä»¶ä½äº /source/favicon.png åˆ™å¡«å†™ "/favicon.png"ï¼‰

# æ¨ªå¹…å›¾ç‰‡
banner:
  enable: true # æ˜¯å¦æ˜¾ç¤ºæ¨ªå¹…å›¾ç‰‡
  url: https://ice.frostsky.com/2024/03/11/76427a856c70ffcf66daa1ebae0e6023.png # æ¨ªå¹…å›¾ç‰‡æ–‡ä»¶è·¯å¾„ï¼Œç›¸å¯¹äº /source ç›®å½•ï¼Œä¹Ÿå¯å¡«å†™ç½‘ç»œå›¾ç‰‡ URL
  position: center # å†³å®šå›¾ç‰‡å°†å¦‚ä½•è¢«è£å‰ªï¼Œå¯¹åº” CSS ä¸­çš„ "object-position" å±æ€§
  onAllPages: true # åœ¨æ‰€æœ‰é¡µé¢ä¸Šæ˜¾ç¤ºæ¨ªå¹…ï¼Œè€Œä¸æ˜¯åªåœ¨é¦–é¡µæ˜¾ç¤º

# å¤–è§‚
hue:
  330 # ä¸»é¢˜è‰²è°ƒ (ä¾‹å¦‚ï¼šçº¢: 0ï¼Œæ©™: 60ï¼Œè“ï¼š260ï¼Œç´«ï¼š300ï¼Œç²‰ï¼š345)
  # å¯è®¿é—® `saicaca.github.io/vivia-preview` é¢„è§ˆé¢œè‰²è®¾ç½®

# ä¸ªäººä¿¡æ¯
avatar: https://avatars.githubusercontent.com/u/42856213?v=4 # å¤´åƒå›¾ç‰‡æ–‡ä»¶è·¯å¾„ï¼Œç›¸å¯¹äº /source ç›®å½•
author: RemMai
subtitle: Love ğŸ§
links:
  # - name: GitLab
  #  icon: fa-brands fa-gitlab # è®¿é—® https://fontawesome.com/search è·å–å›¾æ ‡ä»£ç 
  #  url: http://remmai.com:6500/RemMai
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/RemMai
  - name: Alist
    icon: fa-solid fa-cloud
    url: http://pan.remmai.com:9527
  - name: QQ (2464233121)
    icon: fa-brands fa-qq
    url: tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=2464233121&website=www.oicqzone.com

# ä¾§è¾¹æ 
sidebar:
  widgets: # éœ€è¦å¯ç”¨çš„ç»„ä»¶ (profile, category, tag, archive, recent_posts)
    normal: # éšé¡µé¢æ»šåŠ¨çš„ç»„ä»¶
      - profile
    sticky: # å›ºå®šåœ¨é¡µé¢é¡¶éƒ¨çš„ç»„ä»¶
      - category
      - tag
      - archive
      - recent_posts

# ä¾§è¾¹æ ç»„ä»¶è®¾ç½®
archive_type: "monthly"
recent_posts_limits: 5
categories:
  max_depth: 2 # åˆ†ç±»ç»„ä»¶ä¸­æ˜¾ç¤ºçš„æœ€å¤§ç›®å½•æ·±åº¦ (ç•™ç©ºä¸ºä¸é™åˆ¶)

# ç¬¬ä¸‰æ–¹è¯„è®ºç³»ç»Ÿ
comment:
  valine:
    enable: false # æ˜¯å¦å¯ç”¨ Valine è¯„è®ºç³»ç»Ÿ
    appId:
    appKey:
    placeholder: Just go go
    pageSize: 10
    highlight: true
    serverURLs:
    # å¯åœ¨æ­¤æ·»åŠ å…¶ä»– Valine æ”¯æŒçš„é…ç½®é¡¹
    # è¯¦è§ https://valine.js.org/configuration.html
  twikoo:
    enable: false # æ˜¯å¦å¯ç”¨ Twikoo è¯„è®ºç³»ç»Ÿ
    envID:
    region:
    path: location.pathname
    lang:
    # è¯¦è§ https://github.com/imaegoo/twikoo

#Analytics
gauges_analytics: false
google_analytics: false #UA-xxxxxx
baidu_analytics: false # ddxxxxxxxxxxxxxxxxx In the https://hm.baidu.com/hm.js? Afterwards
